apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-web-deployment
  labels:
    app: devsecops-web
spec:
  replicas: 2
  selector:
    matchLabels:
        app: devsecops-web
  template:
    metadata:
      labels:
        app: devsecops-web
    spec:
      containers:
      - name: web-app
        image: devsecops-web-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10